//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacitbnb.Models
{
    using System;
    using System.Collections.Generic;
    using ulacit_bnb.Models;

    public partial class Accomodation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accomodation()
        {
            this.Review = new HashSet<Review>();
            this.Room = new HashSet<Room>();
        }
    
        public int Acc_ID { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Country { get; set; }
        public string Acc_Zipcode { get; set; }
        public string Acc_State { get; set; }
        public string Acc_Address { get; set; }
        public string Acc_Description { get; set; }
        public string Acc_Evaluation { get; set; }
        public int Hos_ID { get; set; }
    
        public virtual Host Host { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
    }
}
