//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacitbnb.Models
{
    using System;
    using System.Collections.Generic;
    using ulacit_bnb.Models;

    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Identification { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public string Token { get; set; }
    }
}
