//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacitbnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Pay_ID { get; set; }
        public string Pay_Brand { get; set; }
        public string Pay_Type { get; set; }
        public string Pay_Modality { get; set; }
        public System.DateTime Pay_Date { get; set; }
        public int Pay_Amount { get; set; }
        public decimal Pay_Taxes { get; set; }
        public decimal Pay_Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
