//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacitbnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Roo_ID { get; set; }
        public decimal Roo_Price { get; set; }
        public decimal Roo_Quantity { get; set; }
        public string Roo_Type { get; set; }
        public string Roo_Evaluation { get; set; }
        public decimal Roo_BedQuantity { get; set; }
        public int Ser_ID { get; set; }
        public int Acc_ID { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual Service Service { get; set; }
    }
}
