//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacit_bnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        public int AccomodationID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Evaluation { get; set; }
        public int ReviewID { get; set; }
        public int RoomID { get; set; }
        public int HostID { get; set; }
    
        public virtual Host Host { get; set; }
        public virtual Review Review { get; set; }
        public virtual Room Room { get; set; }
    }
}
