//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacit_bnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        public int Acc_ID { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Country { get; set; }
        public string Acc_Zipcode { get; set; }
        public string Acc_State { get; set; }
        public string Acc_Address { get; set; }
        public string Acc_Description { get; set; }
        public string Acc_Evaluation { get; set; }
        public int Rev_ID { get; set; }
        public int Roo_ID { get; set; }
        public int Hos_ID { get; set; }
    
        public virtual Host Host { get; set; }
        public virtual Review Review { get; set; }
        public virtual Room Room { get; set; }
    }
}
