//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacit_bnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public decimal Quantity { get; set; }
        public string ResolutionDate { get; set; }
        public int PaymentID { get; set; }
        public int UserID { get; set; }
        public int RoomID { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
