//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacit_bnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Rev_ID { get; set; }
        public System.DateTime Rev_DateReview { get; set; }
        public int Rev_Rate { get; set; }
        public string Rev_Recommendation { get; set; }
        public string Rev_Comment { get; set; }
        public string Rev_Usefull { get; set; }
        public string Rev_Tittle { get; set; }
        public int Use_ID { get; set; }
        public int Acc_ID { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
        public virtual User User { get; set; }
    }
}
