//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulacit_bnb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.Accomodation = new HashSet<Accomodation>();
        }
    
        public int ReviewID { get; set; }
        public System.DateTime DateReview { get; set; }
        public int Rate { get; set; }
        public string Recommendation { get; set; }
        public string Comment { get; set; }
        public string Usefull { get; set; }
        public string Tittle { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accomodation> Accomodation { get; set; }
        public virtual User User { get; set; }
    }
}
